import { Language } from "../../types";
import { 
  ShoppingCart, 
  MapIcon, 
  ScanLine, 
  Store, 
  Mic, 
  FlaskConical 
} from 'lucide-react';

export const enDashText = {
  news: "Welcome to AI Krishi Mitra",
  welcome_back: "Welcome Back",
  greeting_morning: "Good Morning",
  greeting_afternoon: "Good Afternoon",
  greeting_evening: "Good Evening",
  greeting_night: "Good Night",
  market_rates: "Market Rates",
  live: "Live",
  this_week: "This Week",
  quintal: "/ quintal",
  crop_schedule: "Crop Schedule",
  today_urgent: "Today • Urgent",
  irrigation: "Irrigation (Watering)",
  cotton_field: "Cotton Field • 2 hrs",
  fertilizer: "Fertilizer (NPK)",
  fertilizer_sub: "Tomorrow • 12 Oct",
  tomorrow: "Tomorrow",
  ai_assistant: "AI Krishi Mitra",
  tap_to_ask: "Tap to ask anything",
  crop_doctor_title: "Crop Doctor",
  crop_doctor_sub: "Instant Diagnosis",
  subsidies: "Subsidies & Finance",
  vol: "Arrival",
  high: "High",
  low: "Low",
  weather_desc: {
    0: "Clear Sky",
    1: "Partly Cloudy",
    2: "Partly Cloudy",
    3: "Partly Cloudy",
    45: "Foggy",
    48: "Foggy",
    51: "Light Drizzle",
    53: "Light Drizzle",
    55: "Light Drizzle",
    61: "Moderate Rain",
    63: "Moderate Rain",
    65: "Heavy Rain",
    80: "Rain Showers",
    81: "Rain Showers",
    82: "Rain Showers",
    95: "Thunderstorm"
  },
  crops: {
    'Soyabean': 'Soyabean', 'Cotton': 'Cotton', 'Onion': 'Onion', 'Tur': 'Tur', 'Wheat': 'Wheat', 'Maize': 'Maize', 'Gram': 'Gram', 'Tomato': 'Tomato', 'Potato': 'Potato', 'Rice': 'Rice'
  }
};

export const DASH_TEXT: Record<Language, any> = {
  en: enDashText,
  mr: {
    news: "AI कृषी मित्र मध्ये आपले स्वागत आहे",
    welcome_back: "पुन्हा स्वागत आहे",
    greeting_morning: "शुभ सकाळ",
    greeting_afternoon: "शुभ दुपार",
    greeting_evening: "शुभ संध्याकाळ",
    greeting_night: "शुभ रात्री",
    market_rates: "बाजार भाव",
    live: "थेट",
    this_week: "या आठवड्यात",
    quintal: "/ क्विंटल",
    crop_schedule: "पीक वेळापत्रक",
    today_urgent: "आज • महत्त्वाचे",
    irrigation: "सिंचन (पाणी देणे)",
    cotton_field: "कापूस शेत • २ तास",
    fertilizer: "खत (NPK)",
    fertilizer_sub: "उद्या • १२ ऑक्टोबर",
    tomorrow: "उद्या",
    ai_assistant: "AI कृषी मित्र",
    tap_to_ask: "विचारण्यासाठी टॅप करा",
    crop_doctor_title: "पीक डॉक्टर",
    crop_doctor_sub: "त्वरित रोग निदान",
    subsidies: "सबसिडी आणि आर्थिक मदत",
    vol: "आवक",
    high: "उच्च",
    low: "कमी",
    weather_desc: {
      0: "स्वच्छ आकाश",
      1: "थोडं ढगाळ",
      2: "थोडं ढगाळ",
      3: "थोडं ढगाळ",
      45: "धुके",
      48: "धुके",
      51: "हलकी रिमझिम",
      53: "हलकी रिमझिम",
      55: "हलकी रिमझिम",
      61: "मध्यम पाऊस",
      63: "मध्यम पाऊस",
      65: "मुसळधार पाऊस",
      80: "पावसाच्या सरी",
      81: "पावसाच्या सरी",
      82: "पावसाच्या सरी",
      95: "विजांसह पाऊस"
    },
    crops: {
      'Soyabean': 'सोयाबीन', 'Cotton': 'कापूस', 'Onion': 'कांदा', 'Tur': 'तूर', 'Wheat': 'गहू', 'Maize': 'मका', 'Gram': 'हरभरा', 'Tomato': 'टोमॅटो', 'Potato': 'बटाटा', 'Rice': 'तांदूळ'
    }
  },
  hi: {
    news: "AI कृषि मित्र में आपका स्वागत है",
    welcome_back: "वापसी पर स्वागत है",
    greeting_morning: "शुभ प्रभात",
    greeting_afternoon: "शुभ दोपहर",
    greeting_evening: "शुभ संध्या",
    greeting_night: "शुभ रात्रि",
    market_rates: "मंडी भाव",
    live: "लाइव",
    this_week: "इस सप्ताह",
    quintal: "/ क्विंटल",
    crop_schedule: "फसल अनुसूची",
    today_urgent: "आज • ज़रूरी",
    irrigation: "सिंचाई (पानी देना)",
    cotton_field: "कपास खेत • 2 घंटे",
    fertilizer: "खाद (NPK)",
    fertilizer_sub: "कल • 12 अक्टूबर",
    tomorrow: "कल",
    ai_assistant: "AI कृषि मित्र",
    tap_to_ask: "पूछने के लिए टैप करें",
    crop_doctor_title: "फसल डॉक्टर",
    crop_doctor_sub: "त्वरित रोग निदान",
    subsidies: "सब्सिडी और वित्तीय सहायता",
    vol: "आवक",
    high: "अधिक",
    low: "कम",
    weather_desc: {
      0: "साफ आसमान",
      1: "आंशिक बादल",
      2: "आंशिक बादल",
      3: "आंशिक बादल",
      45: "कोहरा",
      48: "कोहरा",
      51: "हल्की बूंदाबांदी",
      53: "हल्की बूंदाबांदी",
      55: "हल्की बूंदाबांदी",
      61: "मध्यम बारिश",
      63: "मध्यम बारिश",
      65: "भारी बारिश",
      80: "बारिश की बौछारें",
      81: "बारिश की बौछारें",
      82: "बारिश की बौछारें",
      95: "गरज के साथ बारिश"
    },
    crops: {
      'Soyabean': 'सोयाबीन', 'Cotton': 'कपास', 'Onion': 'प्याज', 'Tur': 'तूर', 'Wheat': 'गेहूं', 'Maize': 'मक्का', 'Gram': 'चना', 'Tomato': 'टमाटर', 'Potato': 'आलू', 'Rice': 'चावल'
    }
  },
  te: {
    news: "AI కృషి మిత్రకు స్వాగతం",
    welcome_back: "తిరిగి స్వాగతం",
    greeting_morning: "శుభోదయం",
    greeting_afternoon: "శుభ మధ్యాహ్నం",
    greeting_evening: "శుభ సాయంత్రం",
    greeting_night: "శుభ రాత్రి",
    market_rates: "మార్కెట్ ధరలు",
    live: "ప్రత్యక్ష",
    this_week: "ఈ వారం",
    quintal: "/ క్వింటాల్",
    crop_schedule: "పంట షెడ్యూల్",
    today_urgent: "నేడు • అత్యవసరం",
    irrigation: "నీటి పారుదల",
    cotton_field: "పత్తి పొలం • 2 గంటలు",
    fertilizer: "ఎరువులు (NPK)",
    fertilizer_sub: "రేపు • 12 అక్టోబర్",
    tomorrow: "రేపు",
    ai_assistant: "AI కృషి మిత్ర",
    tap_to_ask: "అడగడానికి నొక్కండి",
    crop_doctor_title: "పంట డాక్టర్",
    crop_doctor_sub: "తక్షణ రోగ నిర్ధారణ",
    subsidies: "సబ్సిడీలు & ఆర్థిక సహాయం",
    vol: "రాక",
    high: "అధిక",
    low: "తక్కువ",
    weather_desc: enDashText.weather_desc,
    crops: enDashText.crops
  },
  ta: {
    news: "AI கிருஷி மித்ராவிற்கு வரவேற்கிறோம்",
    welcome_back: "மீண்டும் வருக",
    greeting_morning: "காலை வணக்கம்",
    greeting_afternoon: "மதிய வணக்கம்",
    greeting_evening: "மாலை வணக்கம்",
    greeting_night: "இரவு வணக்கம்",
    market_rates: "சந்தை விலைகள்",
    live: "நேரலை",
    this_week: "இந்த வாரம்",
    quintal: "/ குவிண்டால்",
    crop_schedule: "பயிர் அட்டவணை",
    today_urgent: "இன்று • அவசரம்",
    irrigation: "நீர்ப்பாசனம்",
    cotton_field: "பருத்தி வயல் • 2 மணி",
    fertilizer: "உரம் (NPK)",
    fertilizer_sub: "நாளை • 12 அக்டோபர்",
    tomorrow: "நாளை",
    ai_assistant: "AI கிருஷி மித்ரா",
    tap_to_ask: "கேட்க தட்டவும்",
    crop_doctor_title: "பயிர் மருத்துவர்",
    crop_doctor_sub: "உடனடி நோய் கண்டறிதல்",
    subsidies: "மானியங்கள் & நிதி",
    vol: "வரத்து",
    high: "அதிக",
    low: "குறைந்த",
    weather_desc: enDashText.weather_desc,
    crops: enDashText.crops
  },
  kn: {
    news: "AI ಕೃಷಿ ಮಿತ್ರಕ್ಕೆ ಸುಸ್ವಾಗತ",
    welcome_back: "ಮತ್ತೆ ಸ್ವಾಗತ",
    greeting_morning: "ಶುಭೋದಯ",
    greeting_afternoon: "ಶುಭ ಮಧ್ಯಾಹ್ನ",
    greeting_evening: "ಶುಭ ಸಂಜೆ",
    greeting_night: "ಶುಭ ರಾತ್ರಿ",
    market_rates: "ಮಾರುಕಟ್ಟೆ ದರಗಳು",
    live: "ಲೈವ್",
    this_week: "ಈ ವಾರ",
    quintal: "/ ಕ್ವಿಂಟಾಲ್",
    crop_schedule: "ಬೆಳೆ ವೇಳಾಪಟ್ಟಿ",
    today_urgent: "ಇಂದು • ತುರ್ತು",
    irrigation: "ನೀರಾವರಿ",
    cotton_field: "ಹತ್ತಿ ಹೊಲ • 2 ಗಂಟೆ",
    fertilizer: "ಗೊಬ್ಬರ (NPK)",
    fertilizer_sub: "ನಾಳೆ • 12 ಅಕ್ಟೋಬರ್",
    tomorrow: "ನಾಳೆ",
    ai_assistant: "AI ಕೃಷಿ ಮಿತ್ರ",
    tap_to_ask: "ಕೇಳಲು ಟ್ಯಾಪ್ ಮಾಡಿ",
    crop_doctor_title: "ಬೆಳೆ ವೈದ್ಯ",
    crop_doctor_sub: "ತ್ವರಿತ ರೋಗ ನಿರ್ಣಯ",
    subsidies: "ಸಬ್ಸಿಡಿಗಳು & ಹಣಕಾಸು",
    vol: "ಆವಕ",
    high: "ಹೆಚ್ಚು",
    low: "ಕಡಿಮೆ",
    weather_desc: enDashText.weather_desc,
    crops: enDashText.crops
  },
  bn: {
    news: "AI কৃষি মিত্রে স্বাগতম",
    welcome_back: "স্বাগতম",
    greeting_morning: "সুপ্রভাত",
    greeting_afternoon: "শুভ দুপুর",
    greeting_evening: "শুভ সন্ধ্যা",
    greeting_night: "শুভ রাত্রি",
    market_rates: "বাজার দর",
    live: "লাইভ",
    this_week: "এই সপ্তাহ",
    quintal: "/ কুইন্টাল",
    crop_schedule: "ফসলের সময়সূচী",
    today_urgent: "আজ • জরুরি",
    irrigation: "সেচ",
    cotton_field: "তুলা খেত • ২ ঘন্টা",
    fertilizer: "সার (NPK)",
    fertilizer_sub: "আগামীকাল • ১২ অক্টোবর",
    tomorrow: "আগামীকাল",
    ai_assistant: "AI কৃষি মিত্র",
    tap_to_ask: "জিজ্ঞাসা করতে ট্যাপ করুন",
    crop_doctor_title: "ফসল ডাক্তার",
    crop_doctor_sub: "তাৎক্ষণিক রোগ নির্ণয়",
    subsidies: "ভর্তুকি ও অর্থায়ন",
    vol: "আমদানি",
    high: "উচ্চ",
    low: "নিম্ন",
    weather_desc: enDashText.weather_desc,
    crops: enDashText.crops
  },
  gu: {
    news: "AI કૃષિ મિત્રમાં આપનું સ્વાગત છે",
    welcome_back: "ફરી સ્વાગત છે",
    greeting_morning: "સુપ્રભાત",
    greeting_afternoon: "શુભ બપોર",
    greeting_evening: "શુભ સાંજ",
    greeting_night: "શુભ રાત્રિ",
    market_rates: "બજાર ભાવ",
    live: "લાઇવ",
    this_week: "આ અઠવાડિયે",
    quintal: "/ ક્વિન્ટલ",
    crop_schedule: "પાક સમયપત્રક",
    today_urgent: "આજે • તાત્કાલિક",
    irrigation: "સિંચાઈ",
    cotton_field: "કપાસ ખેતર • 2 કલાક",
    fertilizer: "ખાતર (NPK)",
    fertilizer_sub: "આવતીકાલે • 12 ઓક્ટોબર",
    tomorrow: "આવતીકાલે",
    ai_assistant: "AI કૃષિ મિત્ર",
    tap_to_ask: "પૂછવા માટે ટેપ કરો",
    crop_doctor_title: "પાક ડોક્ટર",
    crop_doctor_sub: "ત્વરિત રોગ નિદાન",
    subsidies: "સબસિડી અને નાણાકીય સહાય",
    vol: "આવક",
    high: "વધુ",
    low: "ઓછું",
    weather_desc: enDashText.weather_desc,
    crops: enDashText.crops
  },
  pa: {
    news: "AI ਕ੍ਰਿਸ਼ੀ ਮਿੱਤਰ ਵਿੱਚ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ",
    welcome_back: "ਜੀ ਆਇਆਂ ਨੂੰ",
    greeting_morning: "ਸ਼ੁਭ ਸਵੇਰ",
    greeting_afternoon: "ਸ਼ੁਭ ਦੁਪਹਿਰ",
    greeting_evening: "ਸ਼ੁਭ ਸ਼ਾਮ",
    greeting_night: "ਸ਼ੁਭ ਰਾਤ",
    market_rates: "ਮੰਡੀ ਭਾਅ",
    live: "ਲਾਈਵ",
    this_week: "ਇਸ ਹਫ਼ਤੇ",
    quintal: "/ ਕੁਇੰਟਲ",
    crop_schedule: "ਫ਼ਸਲ ਅਨੁਸੂਚੀ",
    today_urgent: "ਅੱਜ • ਜ਼ਰੂਰੀ",
    irrigation: "ਸਿੰਚਾਈ",
    cotton_field: "ਕਪਾਹ ਖੇਤ • 2 ਘੰਟੇ",
    fertilizer: "ਖਾਦ (NPK)",
    fertilizer_sub: "ਕੱਲ੍ਹ • 12 ਅਕਤੂਬਰ",
    tomorrow: "ਕੱਲ੍ਹ",
    ai_assistant: "AI ਕ੍ਰਿਸ਼ੀ ਮਿੱਤਰ",
    tap_to_ask: "ਪੁੱਛਣ ਲਈ ਟੈਪ ਕਰੋ",
    crop_doctor_title: "ਫ਼ਸਲ ਡਾਕਟਰ",
    crop_doctor_sub: "ਤੁਰੰਤ ਰੋਗ ਨਿਦਾਨ",
    subsidies: "ਸਬਸਿਡੀ ਅਤੇ ਵਿੱਤੀ ਸਹਾਇਤਾ",
    vol: "ਆਮਦ",
    high: "ਉੱਚ",
    low: "ਘੱਟ",
    weather_desc: enDashText.weather_desc,
    crops: enDashText.crops
  },
  ml: {
    news: "AI കൃഷി മിത്രയിലേക്ക് സ്വാഗതം",
    welcome_back: "വീണ്ടും സ്വാഗതം",
    greeting_morning: "സുപ്രഭാതം",
    greeting_afternoon: "ശുഭ ഉച്ച",
    greeting_evening: "ശുഭ സായാഹ്നം",
    greeting_night: "ശുഭ രാത്രി",
    market_rates: "വിപണി നിരക്കുകൾ",
    live: "തത്സമയം",
    this_week: "ഈ ആഴ്ച",
    quintal: "/ ക്വിന്റൽ",
    crop_schedule: "വിള ഷെഡ്യൂൾ",
    today_urgent: "ഇന്ന് • അടിയന്തിരം",
    irrigation: "ജലസേചനം",
    cotton_field: "പരുത്തി പാടം • 2 മണിക്കൂർ",
    fertilizer: "വളം (NPK)",
    fertilizer_sub: "നാളെ • 12 ഒക്ടോബർ",
    tomorrow: "നാളെ",
    ai_assistant: "AI കൃഷി മിത്ര",
    tap_to_ask: "ചോദിക്കാൻ ടാപ്പ് ചെയ്യുക",
    crop_doctor_title: "വിള ഡോക്ടർ",
    crop_doctor_sub: "പെട്ടെന്നുള്ള രോഗനിർണ്ണയം",
    subsidies: "സബ്‌സിഡികളും ധനസഹായവും",
    vol: "വരവ്",
    high: "കൂടുതൽ",
    low: "കുറവ്",
    weather_desc: enDashText.weather_desc,
    crops: enDashText.crops
  },
  or: {
    news: "AI କୃଷି ମିତ୍ରକୁ ସ୍ୱାଗତ",
    welcome_back: "ସ୍ୱାଗତ",
    greeting_morning: "ଶୁଭ ସକାଳ",
    greeting_afternoon: "ଶୁଭ ଅପରାହ୍ନ",
    greeting_evening: "ଶୁଭ ସନ୍ଧ୍ୟା",
    greeting_night: "ଶୁଭ ରାତ୍ରି",
    market_rates: "ବଜାର ଦର",
    live: "ଲାଇଭ୍",
    this_week: "ଏହି ସପ୍ତାହ",
    quintal: "/ କ୍ୱିଣ୍ଟାଲ",
    crop_schedule: "ଫସଲ କାର୍ଯ୍ୟସୂଚୀ",
    today_urgent: "ଆଜି • ଜରୁରୀ",
    irrigation: "ଜଳସେଚନ",
    cotton_field: "କପା କ୍ଷେତ • ୨ ଘଣ୍ଟା",
    fertilizer: "ସାର (NPK)",
    fertilizer_sub: "ଆସନ୍ତାକାଲି • ୧୨ ଅକ୍ଟୋବର",
    tomorrow: "ଆସନ୍ତାକାଲି",
    ai_assistant: "AI କୃଷି ମିତ୍ର",
    tap_to_ask: "ପଚାରିବା ପାଇଁ ଟ୍ୟାପ୍ କରନ୍ତୁ",
    crop_doctor_title: "ଫସଲ ଡାକ୍ତର",
    crop_doctor_sub: "ତୁରନ୍ତ ରୋଗ ନିରୂପଣ",
    subsidies: "ସବସିଡି ଏବଂ ଆର୍ଥିକ ସହାୟତା",
    vol: "ଆମଦାନୀ",
    high: "ଅଧିକ",
    low: "କମ",
    weather_desc: enDashText.weather_desc,
    crops: enDashText.crops
  },
  as: {
    news: "AI কৃষি মিত্ৰলৈ স্বাগতম",
    welcome_back: "পুনৰ স্বাগতম",
    greeting_morning: "সুপ্রভাত",
    greeting_afternoon: "শুভ দুপৰীয়া",
    greeting_evening: "শুভ সন্ধিয়া",
    greeting_night: "শুভ ৰাত্ৰি",
    market_rates: "বজাৰ দৰ",
    live: "লাইভ",
    this_week: "এই সপ্তাহ",
    quintal: "/ কুইন্টল",
    crop_schedule: "শস্যৰ সময়সূচী",
    today_urgent: "আজি • জৰুৰী",
    irrigation: "জলসিঞ্চন",
    cotton_field: "কপাহ খেতি • ২ ঘণ্টা",
    fertilizer: "সাৰ (NPK)",
    fertilizer_sub: "কাইলৈ • ১২ অক্টোবৰ",
    tomorrow: "কাইলৈ",
    ai_assistant: "AI কৃষি মিত্ৰ",
    tap_to_ask: "সুধিবলৈ টেপ কৰক",
    crop_doctor_title: "শস্য চিকিৎসক",
    crop_doctor_sub: "তাৎক্ষণিক ৰোগ নিৰ্ণয়",
    subsidies: "সাহায্য আৰু বিত্তীয় সাহায্য",
    vol: "আমদানী",
    high: "উচ্চ",
    low: "নিম্ন",
    weather_desc: enDashText.weather_desc,
    crops: enDashText.crops
  },
};
